// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts         string
	Classes          string
	Deposits         string
	Period           string
	Specialization   string
	Student          string
	StudentsPeriods  string
	StudentsSubjects string
	Subject          string
	Subscription     string
	Teacher          string
	Users            string
}{
	Accounts:         "accounts",
	Classes:          "classes",
	Deposits:         "deposits",
	Period:           "period",
	Specialization:   "specialization",
	Student:          "student",
	StudentsPeriods:  "students_periods",
	StudentsSubjects: "students_subjects",
	Subject:          "subject",
	Subscription:     "subscription",
	Teacher:          "teacher",
	Users:            "users",
}
