// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Periods", testPeriodsUpsert)

	t.Run("Students", testStudentsUpsert)

	t.Run("Subjects", testSubjectsUpsert)

	t.Run("Subscriptions", testSubscriptionsUpsert)

	t.Run("Teachers", testTeachersUpsert)

	t.Run("Users", testUsersUpsert)
}
