[psql]
    dbname = "smarthead"
    host = "localhost"
    port = "5432"
    user = "postgres"
    pass = "docker"
    sslmode = "disable"
    whitelist=[
            "accounts",
            "users",
            "subject",
            "period",
            "teacher",
            "specialization",
            "student",
            "students_periods",
            "students_subjects",
            "deposits",
            "subscription",
            "classes",
            "subsclass",
            "timetable",
            "lesson",
            "lesson_student"
            ]
